<?php defined('SYSPATH') or die('No direct script access.');

class Model_ModPrice extends Model {

    private $_fields;    

    public function __construct()
    {
        $this->_fields = Fields::factory('fldPrice');
    }
    
    /**
     * Виды недвижимостей
     * 
     * @return array 
     */
    public function get_vids()
    {
        return array(
                array('id'=>1,'title'=>'Комнаты, "гостинки"','fields' => $this->_fields->get_fields(1)),
                array('id'=>2,'title'=>'1-комнатные квартиры','fields' => $this->_fields->get_fields(2)),
                array('id'=>3,'title'=>'2-комнатные квартиры','fields' => $this->_fields->get_fields(3)),
                array('id'=>4,'title'=>'3-комнатные квартиры','fields' => $this->_fields->get_fields(4)),
                array('id'=>5,'title'=>'4-комнатные квартиры','fields' => $this->_fields->get_fields(5)),
                array('id'=>6,'title'=>'5-комнатные квартиры','fields' => $this->_fields->get_fields(6)),
                array('id'=>7,'title'=>'Под офис','fields' => $this->_fields->get_fields(7)),
                array('id'=>8,'title'=>'Дома','fields' => $this->_fields->get_fields(8)),
                array('id'=>9,'title'=>'Складские помещения','fields' => $this->_fields->get_fields(9)),
                array('id'=>10,'title'=>'Коммерческая недвижимость','fields' => $this->_fields->get_fields(10)),
                array('id'=>11,'title'=>'Гаражи','fields' => $this->_fields->get_fields(11))
        );
    }
    /**
     * Недвижимость
     * 
     * @return array 
     */
    public function get_data()
    {
        return array(
            1=>array(
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Дзержинского, д.73',
                    'type'=>'общ.',
                    'floor'=>'4/5',
                    'square'=>'17,0',
                    'price'=>'480 000*',
                    'phone'=>'+7 912 659 9048',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Чайковского, д.131а',
                    'type'=>'гост.',
                    'floor'=>'3/5',
                    'square'=>'18',
                    'price'=>'650 000*',
                    'phone'=>'+7 912 659 9048',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Энтузиастов, д.93',
                    'type'=>'общ.',
                    'floor'=>'5/5',
                    'square'=>'17 + 18',
                    'price'=>'735 000',
                    'phone'=>'+7 912 659 9048',
                    'photo'=>'img/no-photo.png',
                ),
            ),
            2=>array(
                array(
                    'rayon'=>'ГГМ',
                    'addres'=>'пр. Октябрьский, д.22',
                    'type'=>'ул.пл.',
                    'floor'=>'7/9',
                    'square'=>'34/18/9',
                    'price'=>'1 360 000',
                    'phone'=>'+7 912 659 9048',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Бобкова, д.10',
                    'type'=>'ул.пл.',
                    'floor'=>'9/10',
                    'square'=>'34/18/9',
                    'price'=>'договорная',
                    'phone'=>'+7 912 659 9048',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Зари, д.56',
                    'type'=>'перех.',
                    'floor'=>'1/5',
                    'square'=>'32/20/6',
                    'price'=>'1 150 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Зари, д.85',
                    'type'=>'ул.пл.',
                    'floor'=>'6/9',
                    'square'=>'34/17/9',
                    'price'=>'1 260 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Зари, д.85',
                    'type'=>'ул.пл.',
                    'floor'=>'9/9',
                    'square'=>'34/17/9',
                    'price'=>'1 150 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ильича, д.76',
                    'type'=>'ул.пл.',
                    'floor'=>'3/9',
                    'square'=>'34/18/9',
                    'price'=>'1 350 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ильича, д.86',
                    'type'=>'ул.пл.',
                    'floor'=>'6/9',
                    'square'=>'34/18/9',
                    'price'=>'1 210 000*',
                    'phone'=>'+7 912 659 9048',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ленинградский, д.44а',
                    'type'=>'хрущ.',
                    'floor'=>'2/5',
                    'square'=>'32/17/6',
                    'price'=>'1 190 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ленинградский, д.57',
                    'type'=>'хрущ.',
                    'floor'=>'2/3',
                    'square'=>'33/19/6',
                    'price'=>'1 105 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ленинградский, д.93',
                    'type'=>'перех.',
                    'floor'=>'2/5',
                    'square'=>'29/16/6',
                    'price'=>'1 150 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Максарева, д.13',
                    'type'=>'ул.пл.',
                    'floor'=>'1/9',
                    'square'=>'34/18/9',
                    'price'=>'1 050 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Свердлова, д.9',
                    'type'=>'перех.',
                    'floor'=>'1/5',
                    'square'=>'31/17/6',
                    'price'=>'840 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Сибирская, д.71',
                    'type'=>'новостр.',
                    'floor'=>'1/9',
                    'square'=>'44/19/12',
                    'price'=>'1 750 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Чайковского, д.44',
                    'type'=>'хрущ.',
                    'floor'=>'1/2',
                    'square'=>'31/19/6',
                    'price'=>'840 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Чайковского, д.133',
                    'type'=>'хрущ.',
                    'floor'=>'4/5',
                    'square'=>'31/19/6',
                    'price'=>'1 150 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Энтузиастов, д.2а',
                    'type'=>'ул.пл.',
                    'floor'=>'7/9',
                    'square'=>'36/18/9',
                    'price'=>'1 250 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Юности, д.94',
                    'type'=>'ул. пл.',
                    'floor'=>'1/9',
                    'square'=>'34/18/9',
                    'price'=>'1 200 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
            ),
            3=>array(
                array(
                    'rayon'=>'Центр',
                    'addres'=>'ул. Мира, д.33',
                    'type'=>'хрущ.',
                    'floor'=>'4/5',
                    'square'=>'43/27/6',
                    'price'=>'1 520 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Тагилстрой',
                    'addres'=>'ул. Огнеупорная, д.5',
                    'type'=>'ул.пл.',
                    'floor'=>'2/5',
                    'square'=>'50/30/9',
                    'price'=>'1 310 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'1 310 000',
                    'addres'=>'ул. Дзержинского, д.65',
                    'type'=>'хрущ.',
                    'floor'=>'3/5',
                    'square'=>'43/28/6',
                    'price'=>'1 365 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Зари, д.2а',
                    'type'=>'ул.пл.',
                    'floor'=>'1/9',
                    'square'=>'50/30/9',
                    'price'=>'1 700 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Зари, д.41',
                    'type'=>'перех.',
                    'floor'=>'2/5',
                    'square'=>'43/27/7',
                    'price'=>'1 680 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Зари, д.81',
                    'type'=>'перех.',
                    'floor'=>'5/5',
                    'square'=>'44/27/7',
                    'price'=>'1 360 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Коминтерна, д.52',
                    'type'=>'хрущ.',
                    'floor'=>'3/5',
                    'square'=>'44/28/6',
                    'price'=>'1 470 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ленинградский, д.56',
                    'type'=>'хрущ.',
                    'floor'=>'3/5',
                    'square'=>'43/27/6',
                    'price'=>'1 550 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ленинградский, д.62',
                    'type'=>'хрущ.',
                    'floor'=>'3/5',
                    'square'=>'41/27/6',
                    'price'=>'1 420 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ленинградский, д.81',
                    'type'=>'хрущ.',
                    'floor'=>'3/5',
                    'square'=>'43/27/6',
                    'price'=>'1 520 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Окунева, д.2а',
                    'type'=>'хрущ.',
                    'floor'=>'5/5',
                    'square'=>'44/27/6',
                    'price'=>'1 170 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Орджоникидзе, д.2',
                    'type'=>'хрущ.',
                    'floor'=>'2/5',
                    'square'=>'42/27/6',
                    'price'=>'1 365 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Орджоникидзе, д.10',
                    'type'=>'хрущ.',
                    'floor'=>'4/5',
                    'square'=>'43/27/6',
                    'price'=>'1 360 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Тимирязева, д.78а',
                    'type'=>'ст.т.',
                    'floor'=>'2/2',
                    'square'=>'45/27/7',
                    'price'=>'1 240 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Энтузиастов, д.20',
                    'type'=>'хрущ.',
                    'floor'=>'2/5',
                    'square'=>'46/29/6',
                    'price'=>'1 575 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'пос. Старатель',
                    'addres'=>'Санаторий Руш, д.13',
                    'type'=>'перех.',
                    'floor'=>'1/5',
                    'square'=>'44/31/6',
                    'price'=>'1 160 0001',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'пос. Северный',
                    'addres'=>'ул. Бирюзовая, д.8',
                    'type'=>'ул.пл.',
                    'floor'=>'2/5',
                    'square'=>'52/30/9',
                    'price'=>'обмен',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'пос. Северный',
                    'addres'=>'ул. Щорса, д.23',
                    'type'=>'перех.',
                    'floor'=>'2/5',
                    'square'=>'45/30/6',
                    'price'=>'790 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Прогород',
                    'addres'=>'Николо-Павловское, ул. Юбилейная, д.7',
                    'type'=>'ул. пл.',
                    'floor'=>'3/5',
                    'square'=>'50/30/9',
                    'price'=>'1 150 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/photo.png',
                ),
            ),
            4=>array(
                array(
                    'rayon'=>'Красный Камень',
                    'addres'=>'ул. Пархоменко, д.141',
                    'type'=>'перех.',
                    'floor'=>'3/5',
                    'square'=>'57/38/6',
                    'price'=>'1 560 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Тагилстрой',
                    'addres'=>'ул. Техническая, д.12',
                    'type'=>'ст.т.',
                    'floor'=>'2/2',
                    'square'=>'80/52/8',
                    'price'=>'1 220 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Вагоностроителей, д.13',
                    'type'=>'ст.т.',
                    'floor'=>'4/4',
                    'square'=>'75/56/12',
                    'price'=>'2 600 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Вагоностроителей, д.13 / ул. Бажова, д.6',
                    'type'=>'ст.т.',
                    'floor'=>'1/4',
                    'square'=>'58',
                    'price'=>'2 100 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Валегинская, д.7',
                    'type'=>'ул.пл.',
                    'floor'=>'9/10',
                    'square'=>'62/38/9',
                    'price'=>'1 930 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ильича, д.5',
                    'type'=>'хрущ.',
                    'floor'=>'3/5',
                    'square'=>'56/42/6',
                    'price'=>'1 660 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ленинградский, д.56',
                    'type'=>'хрущ.',
                    'floor'=>'3/5',
                    'square'=>'56/43/6',
                    'price'=>'1 650 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ленинградский, д.85',
                    'type'=>'хрущ.',
                    'floor'=>'2/5',
                    'square'=>'56/42/6',
                    'price'=>'1 940 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Патона, д.5',
                    'type'=>'ст.т.',
                    'floor'=>'2/4',
                    'square'=>'58/40/7',
                    'price'=>'2 600 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Чайковского, д.90',
                    'type'=>'инд.пл.',
                    'floor'=>'5/5',
                    'square'=>'60/38/8',
                    'price'=>'1 870 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Энтузиастов, д.3',
                    'type'=>'хрущ.',
                    'floor'=>'1/5',
                    'square'=>'54/41/6',
                    'price'=>'1 400 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'пос. Северный',
                    'addres'=>'ул. 9 Января, д.7',
                    'type'=>'перех.',
                    'floor'=>'2/5',
                    'square'=>'60/43/6',
                    'price'=>'1 230 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
            ),
            5=>array(
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Вагоностроителей, д.59',
                    'type'=>'ул.пл.',
                    'floor'=>'3/9',
                    'square'=>'74/49/9',
                    'price'=>'2к. кв. ул.пл.',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Юности, д.22',
                    'type'=>'ул.пл.',
                    'floor'=>'9/9',
                    'square'=>'74/49/9',
                    'price'=>'2 490 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
            ),
            6=>array(
                array(
                    'rayon'=>'Центр',
                    'addres'=>'ул. Газетная, д.75',
                    'type'=>'инд.пл.',
                    'floor'=>'5/5',
                    'square'=>'110/ /25',
                    'price'=>'3 850 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
            ),
            7=>array(
                array(
                    'rayon'=>'Тагилстрой',
                    'addres'=>'ул. Гастелло, д.3',
                    'type'=>'отд.зд.',
                    'floor'=>'',
                    'square'=>'425+200',
                    'price'=>'8 100 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Вагоностроителей, д.13 / ул. Бажова, д.6',
                    'type'=>'ст.т.',
                    'floor'=>'1/4',
                    'square'=>'58',
                    'price'=>'2 100 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Ленинградский, д.77',
                    'type'=>'хрущ.',
                    'floor'=>'1/5',
                    'square'=>'43',
                    'price'=>'1 450 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Сибирская, д.71',
                    'type'=>'новостр.',
                    'floor'=>'1/9',
                    'square'=>'44/19/12',
                    'price'=>'1 570 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
            ),
            8=>array(
                array(
                    'rayon'=>'Центр',
                    'addres'=>'ул. Менеделеева',
                    'type'=>'бр.',
                    'floor'=>'13 сот.',
                    'square'=>'50',
                    'price'=>'900 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Выя',
                    'addres'=>'ул. Энергетиков',
                    'type'=>'1/4',
                    'floor'=>'3 сот.',
                    'square'=>'33',
                    'price'=>'договорная',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Н. Кушва',
                    'addres'=>'ул. Ползунова',
                    'type'=>'бр.',
                    'floor'=>'9,5 сот.',
                    'square'=>'30',
                    'price'=>'980 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Н. Кушва',
                    'addres'=>'ул. Степная',
                    'type'=>'бр.',
                    'floor'=>'6 сот.',
                    'square'=>'52,6',
                    'price'=>'2 790 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Исинская',
                    'type'=>'кирп.',
                    'floor'=>'8 сот.',
                    'square'=>'242',
                    'price'=>'3 350 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Киевская',
                    'type'=>'зем. уч-к',
                    'floor'=>'10 сот.',
                    'square'=>'',
                    'price'=>'340 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Рудник',
                    'addres'=>'ул. Ракетная',
                    'type'=>'ш/б',
                    'floor'=>'6 сот.',
                    'square'=>'36',
                    'price'=>'1 550 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Пригород',
                    'addres'=>'д. Беляковка, Мичуринская',
                    'type'=>'бр.',
                    'floor'=>'19 сот.',
                    'square'=>'14',
                    'price'=>'330 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Пригород',
                    'addres'=>'Быньги, Нагорная',
                    'type'=>'бр.',
                    'floor'=>'8 сот.',
                    'square'=>'25+14',
                    'price'=>'1 550 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Пригород',
                    'addres'=>'с. Покровское, ул. Садовая',
                    'type'=>'зем. уч-к',
                    'floor'=>'8,5 сот.',
                    'square'=>'',
                    'price'=>'430 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
            ),
            9=>array(
                array(
                    'rayon'=>'Кушва',
                    'addres'=>'ул. Расковой',
                    'type'=>'',
                    'floor'=>'',
                    'square'=>'',
                    'price'=>'2 200 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
            ),
            10=>array(
                array(
                    'rayon'=>'ГГМ',
                    'addres'=>'ул. Октябрьский, д.22',
                    'type'=>'магазин',
                    'floor'=>'',
                    'square'=>'55+7',
                    'price'=>'3 900 000',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Н. Кушва',
                    'addres'=>'ул. Степная',
                    'type'=>'произв.',
                    'floor'=>'6 сот.',
                    'square'=>'200',
                    'price'=>'2 790 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'Н. Кушва',
                    'addres'=>'ул. Железнодорожная',
                    'type'=>'автосервис',
                    'floor'=>'',
                    'square'=>'6 сот.',
                    'price'=>'5 100 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
            ),
            11=>array(
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'"Маяк"',
                    'type'=>'',
                    'floor'=>'',
                    'square'=>'3*6',
                    'price'=>'250 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'"Чайка"',
                    'type'=>'',
                    'floor'=>'',
                    'square'=>'6*8',
                    'price'=>'530 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
                array(
                    'rayon'=>'УВЗ',
                    'addres'=>'ул. Окунева, д.22',
                    'type'=>'',
                    'floor'=>'',
                    'square'=>'7*7',
                    'price'=>'1 595 000*',
                    'phone'=>'+7 912 659 9048 ',
                    'photo'=>'img/no-photo.png',
                ),
            ),
        );
    }
} 
